version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      # Install dependencies needed for running tests
      - npm install

  pre_build:
    commands:
      # Discover and run unit tests in the 'tests' directory
  post_build:
    commands:
      # Remove existing node_modules to clear dev dependencies
      - rm -r node_modules

      # Install runtime dependencies
      - npm install --production

artifacts:
  type: zip
  files:
    - '**/*'
    - app.js
    - package.json
    - package-lock.json
